'use strict'

const fs = require('fs')
const path = require('path')

/**
 * Build the QBF cache directory that Vite uses as its root.
 *
 * We never touch the user's source tree. Instead we generate, inside
 * node_modules/.qbf:
 *
 *   index.html  – the document Electron loads, with a #root mount node.
 *   entry.ts    – a one-line shim that imports the user's real entry file.
 *
 * Keeping the html inside a directory we control means the exact same setup
 * works for both `vite` (dev server) and `vite build`, which both require the
 * html to live within the configured root.
 */
function prepareAppDir({ qbfDir, entry, appName }) {
  fs.mkdirSync(qbfDir, { recursive: true })

  const entryShim = path.join(qbfDir, 'entry.ts')
  const htmlFile = path.join(qbfDir, 'index.html')

  // Relative path from the shim to the user's entry, with posix separators so
  // it is a valid ES module specifier on every platform.
  let rel = path.relative(qbfDir, entry).split(path.sep).join('/')
  if (!rel.startsWith('.')) rel = './' + rel

  writeIfChanged(
    entryShim,
    `// Generated by quick-brown-fox. Do not edit.\nimport ${JSON.stringify(rel)}\n`
  )

  writeIfChanged(
    htmlFile,
    `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta
      http-equiv="Content-Security-Policy"
      content="default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self'"
    />
    <title>${escapeHtml(appName)}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="./entry.ts"></script>
  </body>
</html>
`
  )

  return { htmlFile, entryShim }
}

function writeIfChanged(file, content) {
  let current = null
  try {
    current = fs.readFileSync(file, 'utf8')
  } catch {
    /* not there yet */
  }
  if (current !== content) fs.writeFileSync(file, content)
}

function escapeHtml(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

module.exports = { prepareAppDir }
