'use strict'

const fs = require('fs')
const path = require('path')

// Production CSP: lock down to self, but allow the renderer to reach the local
// server on any localhost port (the exact port is chosen at runtime).
const PROD_CSP =
  "default-src 'self'; " +
  "connect-src 'self' http://localhost:* http://127.0.0.1:* ws://localhost:* ws://127.0.0.1:*; " +
  "img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self'"

/**
 * Build the QBF cache directory that Vite uses as its root.
 *
 * We never touch the user's source tree. Instead we generate, inside
 * node_modules/.qbf:
 *
 *   index.html   – the document Electron loads, with a #root mount node.
 *   entry.ts     – a one-line shim that imports the user's real UI entry.
 *
 * Keeping the html inside a directory we control means the exact same setup
 * works for both `vite` (dev server) and `vite build`, which both require the
 * html to live within the configured root.
 */
function prepareAppDir({ qbfDir, entry, appName }, mode = 'development') {
  fs.mkdirSync(qbfDir, { recursive: true })

  const entryShim = path.join(qbfDir, 'entry.ts')
  const htmlFile = path.join(qbfDir, 'index.html')

  writeIfChanged(
    entryShim,
    `// Generated by quick-brown-fox. Do not edit.\nimport ${JSON.stringify(relSpecifier(qbfDir, entry))}\n`
  )

  // A strict CSP in dev breaks Vite's HMR (inline/eval), so we only emit it
  // for production builds.
  const csp =
    mode === 'production'
      ? `\n    <meta http-equiv="Content-Security-Policy" content="${PROD_CSP}" />`
      : ''

  writeIfChanged(
    htmlFile,
    `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />${csp}
    <title>${escapeHtml(appName)}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="./entry.ts"></script>
  </body>
</html>
`
  )

  return { htmlFile, entryShim }
}

/**
 * Generate the server entry shim: a tiny module that re-exports the user's
 * server handler so Vite can bundle it as a single SSR/CJS file.
 */
function prepareServerShim({ qbfDir, server }) {
  fs.mkdirSync(qbfDir, { recursive: true })
  const shim = path.join(qbfDir, 'server-shim.ts')
  writeIfChanged(
    shim,
    `// Generated by quick-brown-fox. Do not edit.\n` +
      `export { default } from ${JSON.stringify(relSpecifier(qbfDir, server.entry))}\n`
  )
  return { shim }
}

// Relative ES module specifier from `fromDir` to `target`, posix-separated and
// always prefixed so it is a valid specifier on every platform.
function relSpecifier(fromDir, target) {
  let rel = path.relative(fromDir, target).split(path.sep).join('/')
  if (!rel.startsWith('.')) rel = './' + rel
  return rel
}

function writeIfChanged(file, content) {
  let current = null
  try {
    current = fs.readFileSync(file, 'utf8')
  } catch {
    /* not there yet */
  }
  if (current !== content) fs.writeFileSync(file, content)
}

function escapeHtml(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

module.exports = { prepareAppDir, prepareServerShim }
