'use strict'

const fs = require('fs')
const path = require('path')

// Production CSP: lock down to self, but allow the renderer to reach the local
// server on any localhost port (the exact port is chosen at runtime).
const PROD_CSP =
  "default-src 'self'; " +
  "connect-src 'self' http://localhost:* http://127.0.0.1:* ws://localhost:* ws://127.0.0.1:*; " +
  "img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self'"

/**
 * Build the QBF cache directory that Vite uses as its root.
 *
 * We never touch the user's source tree. Instead we generate, inside
 * node_modules/.qbf:
 *
 *   index.html   – the document Electron loads, with a #root mount node.
 *   entry.ts     – a one-line shim that imports the user's real UI entry.
 *
 * Keeping the html inside a directory we control means the exact same setup
 * works for both `vite` (dev server) and `vite build`, which both require the
 * html to live within the configured root.
 */
function prepareAppDir({ qbfDir, entry, appName, framework }, mode = 'development') {
  fs.mkdirSync(qbfDir, { recursive: true })

  const entryShim = path.join(qbfDir, 'entry.ts')
  const htmlFile = path.join(qbfDir, 'index.html')
  const renderShim = path.join(qbfDir, 'render.ts')

  writeIfChanged(
    entryShim,
    `// Generated by quick-brown-fox. Do not edit.\nimport ${JSON.stringify(relSpecifier(qbfDir, entry))}\n`
  )
  writeIfChanged(renderShim, rendererCode(framework && framework.name))

  // A strict CSP in dev breaks Vite's HMR (inline/eval), so we only emit it
  // for production builds.
  const csp =
    mode === 'production'
      ? `\n    <meta http-equiv="Content-Security-Policy" content="${PROD_CSP}" />`
      : ''

  writeIfChanged(
    htmlFile,
    `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />${csp}
    <title>${escapeHtml(appName)}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="./entry.ts"></script>
  </body>
</html>
`
  )

  return { htmlFile, entryShim, renderShim }
}

/**
 * Generate the server entry shim: a tiny module that re-exports the user's
 * server handler so Vite can bundle it as a single SSR/CJS file.
 */
function prepareServerShim({ qbfDir, server }) {
  fs.mkdirSync(qbfDir, { recursive: true })
  const shim = path.join(qbfDir, 'server-shim.ts')
  writeIfChanged(
    shim,
      `// Generated by quick-brown-fox. Do not edit.\n` +
      `import * as mod from ${JSON.stringify(relSpecifier(qbfDir, server.entry))}\n` +
      `const pick = (name) => mod[name]\n` +
      `const handler = mod.default || pick('handler') || pick('server') || mod\n` +
      `export default handler\n`
  )
  return { shim }
}

function rendererCode(frameworkName) {
  const common = `
function resolveTarget(target) {
  const resolved =
    typeof target === 'string'
      ? document.querySelector(target)
      : target || document.getElementById('root')
  if (!resolved) {
    throw new Error('quick-brown-fox could not find a mount target. Pass { target } or add <div id="root"></div>.')
  }
  return resolved
}
`

  switch (frameworkName || 'react') {
    case 'solid':
      return `// Generated by quick-brown-fox. Do not edit.
import { createComponent } from 'solid-js'
import { render as solidRender } from 'solid-js/web'
${common}
export function render(Component, options = {}) {
  return solidRender(() => createComponent(Component, options.props || {}), resolveTarget(options.target))
}
export default render
`
    case 'vue':
      return `// Generated by quick-brown-fox. Do not edit.
import { createApp } from 'vue'
${common}
export function render(Component, options = {}) {
  const app = createApp(Component, options.props || {})
  app.mount(resolveTarget(options.target))
  return app
}
export default render
`
    case 'svelte':
      return `// Generated by quick-brown-fox. Do not edit.
import { mount } from 'svelte'
${common}
export function render(Component, options = {}) {
  return mount(Component, {
    target: resolveTarget(options.target),
    props: options.props || {},
  })
}
export default render
`
    case 'vanilla':
      return `// Generated by quick-brown-fox. Do not edit.
${common}
export function render(Component, options = {}) {
  const target = resolveTarget(options.target)
  const result = typeof Component === 'function' ? Component({ target, props: options.props || {} }) : Component
  if (result instanceof Node) target.appendChild(result)
  else if (typeof result === 'string') target.innerHTML = result
  return result
}
export default render
`
    case 'react':
    default:
      return `// Generated by quick-brown-fox. Do not edit.
import React from 'react'
import { createRoot } from 'react-dom/client'
${common}
export function render(Component, options = {}) {
  const target = resolveTarget(options.target)
  const root = createRoot(target)
  const element = React.isValidElement(Component)
    ? Component
    : React.createElement(Component, options.props || {})
  root.render(element)
  return root
}
export default render
`
  }
}

// Relative ES module specifier from `fromDir` to `target`, posix-separated and
// always prefixed so it is a valid specifier on every platform.
function relSpecifier(fromDir, target) {
  let rel = path.relative(fromDir, target).split(path.sep).join('/')
  if (!rel.startsWith('.')) rel = './' + rel
  return rel
}

function writeIfChanged(file, content) {
  let current = null
  try {
    current = fs.readFileSync(file, 'utf8')
  } catch {
    /* not there yet */
  }
  if (current !== content) fs.writeFileSync(file, content)
}

function escapeHtml(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

module.exports = { prepareAppDir, prepareServerShim }
